import type {Metadata} from "next";
import {Geist_Mono, Montserrat} from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
	variable: "--font-montserrat-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: "Emma Lucas",
	description: "Generated by create next app",
};

export default function RootLayout({
												  children,
											  }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body
			className={`${montserrat.className} antialiased`}
		>
		{children}
		</body>
		</html>
	);
}
